spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080